# -*- coding: utf-8 -*-
#AmendEmployeeScreen

ADMIN_PASS_INCORRECT = u"Das Administrator-Passwort war falsch."
AMEND_BUTTON_TEXT = u"Änderung"
AMEND_BY_TEXT = u"Feld zu ändern: "
AMEND_EMP_SCREEN_NONETYPE_ERROR_TEXT = u"Bitte geben Sie die Änderung Kriterien."
AMEND_FOR_TEXT = u"Zu ändern:"
AMEND_EMPLOYEES_TEXT = u"Ändern eines Datensatzes: "
BACK_BUTTON_TEXT = u"Zurück"
CODE_TEXT = u"Code"
DEPARTMENT_TEXT = u"Abteilung"
DOB_TEXT = u"DOB"
DROPDOWN_DEPARTMENT_TEXT = u"Abteilung"
DROPDOWN_DOB_TEXT = u"DOB"
DROPDOWN_EMPCODE_TEXT = u"Mitarbeiter-Code"
DROPDOWN_NAME_TEXT = u"Name"
DROPDOWN_SALARY_TEXT = u"Gehalt"
EMP_CODE_TEXT = u"Mitarbeiter-Code"
GENDER_TEXT = u"Geschlecht"
HELP_OPTION_TEXT = u"Hier können Sie Mitarbeiterdaten durch Feld ändern."
NAME_TEXT = u"Name"
NO_EMP_RECORDS_TEXT = u"Es gibt keine Mitarbeiterdatensätzen."
REGISTER_BUTTON_TEXT = u"Benutzerkonto erstellen"
SALARY_TEXT = u"Gehalt"
