#AmendEmployeeScreen

AMEND_BUTTON_TEXT = u"Amend"
AMEND_BY_TEXT = u"Amend Field : "
AMEND_EMP_SCREEN_NONETYPE_ERROR_TEXT = u"Please enter Amendment Criteria."
AMEND_FOR_TEXT = u"Amend to : "
AMEND_FOR_EMPLOYEES_TEXT = u"Amend a Record : "
BACK_BUTTON_TEXT = u"Back"
CODE_TEXT = u"Code"
DEPARTMENT_TEXT = u"Department"
DOB_TEXT = u"DOB"
DROPDOWN_DEPARTMENT_TEXT = u"Department"
DROPDOWN_DOB_TEXT = u"DOB"
DROPDOWN_EMPCODE_TEXT = u"Employee Code"
DROPDOWN_NAME_TEXT = u"Name"
DROPDOWN_SALARY_TEXT = u"Salary"
EMP_CODE_TEXT = u"Employee Code"
GENDER_TEXT = u"Gender"
HELP_OPTION_TEXT = u"Here you can amend employee records by field."
INVALID_DOB_TEXT = u"Please enter a valid DOB (DD/MM/YYYY)"
NAME_TEXT = u"Name"
NO_EMP_RECORDS_TEXT = u"There are no employee records."
SALARY_TEXT = u"Salary"
