#CONSTANTS

VERSION_NUMBER = "2.2.2"

WINDOW_GEOMETRY = "900x600+200+50"

WINDOW_TITLE = ""

RESERVED_NAMES = ["Administrator", "Admin"] #This will Disallow names.

HELP_SYMBOL = u"?"

#File Handling Methods

APPEND_MODE = "a"
APPEND_BINARY_MODE = "ab"
READ_MODE = "r"
READ_BINARY_MODE = "rb"
WRITE_MODE = "w"
WRITE_BINARY_MODE = "wb"

#File Names

ADMIN_PASS_FILENAME = "AdminPass.txt"
COPYRIGHT_IMAGE_FILENAME = "CopyrightNotice.gif"
CURRENT_EMP_FILENAME = "CurrentEmployee.txt"
EMPCODE_FILENAME = "EmpCodes.p"
EMP_COUNT_FILENAME = 'EmpCount.txt'
EMP_DATABASE_FILENAME = "EmpDatabase.txt"
INITIAL_SETUP_FILENAME = "InitialSetup.txt"
LANGUAGE_FILENAME = "Language.txt"
LOG_FILENAME = "Log.txt"
LOGIN_DATA_FILENAME = "LoginData.p"
LOGIN_SECURITY_FILENAME = "LoginAttempts.p"
LOGO_GIF_FILENAME = "EmpTrackerImage.gif"
TOTAL_EXPENDITURE_FILENAME = "TotalExpenditure.txt"
TOTAL_SALARY_FILENAME = "TotalSalary.txt"

#Time Periods

DAYS_IN_A_YEAR = 365.25
WEEKS_IN_A_YEAR = 52
MONTHS_IN_A_YEAR = 12
QUARTERLY_MONTHS = 4
BIANNUAL_MONTHS = 2

#Tax Values

BAND_ZERO_TAX_LIMIT = 10000
BAND_ONE_TAX_LIMIT = 31865
BAND_TWO_TAX_LIMIT = 150000

BAND_ONE_TAX = 0.2
BAND_TWO_TAX = 0.4
BAND_THREE_TAX = 0.45


