# -*- coding: utf-8 -*-
#CreateEmployeeScreen

CES_BACK_BUTTON_TEXT = u"Zurück"
CES_CODE_TEXT = u"Code"
CES_DEPARTMENT_TEXT = u"Abteilung"
CES_DEPARTMENT_HELP_TEXT =u"Das ist aktuelle Abteilung des Mitarbeiters"
CES_DOB_TEXT = u"DOB"
CES_DOB_HELP_TEXT = u"Dies ist der Mitarbeiter Geburtsdatum"
CES_GENDER_TEXT = u"Geschlecht"
CES_GENDER_HELP_TEXT = u"Dies ist die Mitarbeiter-Geschlecht (M/F)"
CES_HELP_TEXT = u"Hier können Sie eine neue Mitarbeiterdatensatz erstellen. Füllen Sie die Felder aus und klicken Sie auf 'einreichenn', um dies zu tun."
CES_NAME_TEXT = u"Name"
CES_NAME_HELP_TEXT = u"Dies ist den Namen des Mitarbeiters - Vorname & Name"
CES_SALARY_TEXT = u"Gehalt"
CES_SALARY_HELP_TEXT = u"Dies ist die Mitarbeiter-Gehalt pro Jahr (nur eine Nummer: 23000)"
CES_SUBMIT_BUTTON_TEXT = u"einreichen"
EMP_DEPARTMENT_LABEL_TEXT = u'Mitarbeiter Abteilung'
EMP_DEPARTMENT_LABEL_TWO_TEXT = u'Erneute Abteilung'
EMP_DEPARTMENT_MISMATCH_TEXT = u"Der Mitarbeiter Abteilungen nicht überein."
EMP_DOB_INVALID_TEXT = u"Bitte geben Sie eine gültige DOB."
EMP_DOB_LABEL_TEXT = u'Mitarbeiter DOB (TT/MM/JJJJ)'
EMP_DOB_LABEL_TWO_TEXT = u'Erneute DOB (TT/MM/JJJJ)'
EMP_DOB_MISMATCH_TEXT = u"Der Mitarbeiter DOB nicht überein."
EMP_GENDER_INVALID_TEXT = u"Bitte geben Sie eine gültige Geschlecht."
EMP_GENDER_LABEL_TEXT = u'Mitarbeiter Geschlecht'
EMP_GENDER_LABEL_TWO_TEXT = u'Erneute Geschlecht'
EMP_GENDER_MISMATCH_TEXT = u"Der Mitarbeiter Genders nicht überein."
EMP_NAME_LABEL_TEXT = u'Name des Mitarbeiters'
EMP_NAME_LABEL_TWO_TEXT = u'Erneute Namens'
EMP_NAME_MISMATCH_TEXT = u"Die Mitarbeiternamen stimmen nicht überein."
EMP_SALARY_INVALID_TEXT = u"Bitte geben Sie eine gültige Gehalt."
EMP_SALARY_LABEL_TEXT = u'Mitarbeiter Gehalts'
EMP_SALARY_LABEL_TWO_TEXT = u'Erneute Gehalts'
EMP_SALARY_MISMATCH_TEXT = u"Die Gehälter der Beschäftigten nicht überein."
NO_EMP_DEPARTMENT_TEXT = u"Bitte eingeben / Bestätigen des Mitarbeiters Abteilung."
NO_EMP_DOB_TEXT = u"Bitte eingeben / Bestätigen des Mitarbeiters DOB"
NO_EMP_GENDER_TEXT = u"Bitte eingeben / Bestätigen des Arbeitnehmers Geschlecht."
NO_EMP_NAME_TEXT = u"Bitte eingeben / bestätigen den Namen des Mitarbeiters."
NO_EMP_SALARY_TEXT = u"Bitte eingeben / Bestätigen des Mitarbeiters Gehalt."
