#CreateEmployeeScreen

CES_BACK_BUTTON_TEXT = u"Back"
CES_CODE_TEXT = u"Code"
CES_DEPARTMENT_TEXT = u"Department"
CES_DEPARTMENT_HELP_TEXT =u"This is the Employee's current Department"
CES_DOB_TEXT = u"DOB"
CES_DOB_HELP_TEXT = u"This is the Employee's Date of Birth"
CES_GENDER_TEXT = u"Gender"
CES_GENDER_HELP_TEXT = u"This is the Employee's Gender (M/F)"
CES_HELP_TEXT = u"Here you can create a new Employee Record. Fill in the fields, and click 'Submit' to do so."
CES_NAME_TEXT = u"Name"
CES_NAME_HELP_TEXT = u"This is the Employee's Name - Forename & Surname"
CES_SALARY_TEXT = u"Salary"
CES_SALARY_HELP_TEXT = u"This is the Employee's Salary per annum (Just a number : i.e. 23000)"
CES_SUBMIT_BUTTON_TEXT = u"Submit"
EMP_DEPARTMENT_LABEL_TEXT = u'Employee Department'
EMP_DEPARTMENT_LABEL_TWO_TEXT = u'Reenter Department'
EMP_DEPARTMENT_MISMATCH_TEXT = u"The Employee Departments didn't match."
EMP_DOB_INVALID_TEXT = u"Please enter a valid DOB."
EMP_DOB_LABEL_TEXT = u'Employee DOB (DD/MM/YYYY)'
EMP_DOB_LABEL_TWO_TEXT = u'Reenter DOB (DD/MM/YYYY)'
EMP_DOB_MISMATCH_TEXT = u"The Employee DOB's didn't match."
EMP_GENDER_INVALID_TEXT = u"Please enter a valid gender."
EMP_GENDER_LABEL_TEXT = u'Employee Gender'
EMP_GENDER_LABEL_TWO_TEXT = u'Reenter Gender'
EMP_GENDER_MISMATCH_TEXT = u"The Employee Genders didn't match."
EMP_NAME_LABEL_TEXT = u'Employee Name'
EMP_NAME_LABEL_TWO_TEXT = u'Reenter Name'
EMP_NAME_MISMATCH_TEXT = u"The Employee Names didn't match."
EMP_SALARY_INVALID_TEXT = u"Please enter a valid Salary."
EMP_SALARY_LABEL_TEXT = u'Employee Salary'
EMP_SALARY_LABEL_TWO_TEXT = u'Reenter Salary'
EMP_SALARY_MISMATCH_TEXT = u"The Employee Salaries didn't match."
NO_EMP_DEPARTMENT_TEXT = u"Please Enter/Confirm the Employee's Department."
NO_EMP_DOB_TEXT = u"Please Enter/Confirm the Employee's DOB"
NO_EMP_GENDER_TEXT = u"Please Enter/Confirm the Employee's Gender."
NO_EMP_NAME_TEXT = u"Please Enter/Confirm the Employee's Name."
NO_EMP_SALARY_TEXT = u"Please Enter/Confirm the Employee's Salary."
