#MainScreen

EMP_MENU_AMEND_TEXT = u"Änderung eines Feld in einem Datensatz"
EMP_MENU_CREATE_TEXT = u"Neue Mitarbeiterdatensatz"
EMP_MENU_DELETE_TEXT = u"Löschen eines Mitarbeiterdatensatz"
EMP_MENU_SEARCH_TEXT = u"Nach einem Mitarbeiter Rekord"
EMP_SUBMENU_DEPARTMENT_TEXT = u"Abteilung"
EMP_SUBMENU_DOB_TEXT = u"DOB"
EMP_SUBMENU_GENDER_TEXT = u"Geschlecht"
EMP_SUBMENU_NAME_TEXT = u"Name"
EMP_SUBMENU_SALARY_TEXT = u"Gehalt"
EXP_MENU_ADD_EXP_TEXT = u"Ausgaben hinzufügen"
EXP_MENU_DEDUCT_EXP_TEXT = u"Ausgaben abziehen"
EXP_MENU_TOTAL_TEXT = u"Gesamt"
EXP_SUBMENU_DAILY_TEXT = u"Täglich"
EXP_SUBMENU_MONTHLY_TEXT = u"Monatlich"
EXP_SUBMENU_WEEKLY_TEXT = u"Wöchentlich"
EXP_SUBMENU_YEARLY_TEXT = u"Jährlich"
MAIN_SCREEN_HELP_TEXT = u"Dies ist der Hauptbildschirm . Von hier aus können zahlreiche Operationen durchführen können. Verwenden Sie die Menüleiste, um sie zu finden."
MENUBAR_EMPLOYEES_TEXT = u"Mitarbeiter"
MENUBAR_EXPENDITURE_TEXT = u"Ausgaben"
MENUBAR_FILE_TEXT = u"Datei"
