#MainScreen

EMP_COUNT_POPUP_TEXT = u"Employee Count : %s"
EMP_COUNT_TEXT = u"Display Total Employee Count"
EMP_MENU_AMEND_TEXT = u"Amend a Field in a Record"
EMP_MENU_CREATE_TEXT = u"Create new Employee Record"
EMP_MENU_DELETE_TEXT = u"Delete an Employee Record"
EMP_MENU_SEARCH_TEXT = u"Search for an Employee Record"
EMP_SUBMENU_DEPARTMENT_TEXT = u"Department"
EMP_SUBMENU_DOB_TEXT = u"DOB"
EMP_SUBMENU_GENDER_TEXT = u"Gender"
EMP_SUBMENU_NAME_TEXT = u"Name"
EMP_SUBMENU_SALARY_TEXT = u"Salary"
EXP_MENU_ADD_EXP_TEXT = u"Add Expenditure"
EXP_MENU_DEDUCT_EXP_TEXT = u"Deduct Expenditure"
EXP_MENU_TOTAL_TEXT = u"Total"
EXP_SUBMENU_DAILY_TEXT = u"Daily"
EXP_SUBMENU_MONTHLY_TEXT = u"Monthly"
EXP_SUBMENU_WEEKLY_TEXT = u"Weekly"
EXP_SUBMENU_YEARLY_TEXT = u"Yearly"
MAIN_SCREEN_HELP_TEXT = u"This is the main screen. From here, you can perform numerous operations. Use the menu bar to find them."
MENUBAR_EMPLOYEES_TEXT = u"Employees"
MENUBAR_EXPENDITURE_TEXT = u"Expenditure"
MENUBAR_FILE_TEXT = u"File"
TOTAL_EXP_TEXT = u"Display Total Expenditure"
TOTAL_SALARY_TEXT = u"Display Total Salary"
TOTALS_MENU_TEXT = u"Totals"
