#RegisterScreen

DMIN_PASS_LABEL_TEXT = u'Administrator Password'
BACK_BUTTON_TEXT = u"Back"
EMP_ACCOUNT_CREATED_TEXT = u"Employee Account Created."
EMP_LOGIN_HELP_TEXT = u"This is the Employee's unique login."
EMP_LOGIN_LABEL_TEXT = u'Employee Login'
EMP_LOGIN_LABEL_TWO_TEXT = u'Reenter Employee Login'
EMP_PASS_HELP_TEXT = u"Employee Passwords must be 8 Characters Long, and contain at least 1 uppercase character, 1 lowercase character and 1 digit."
EMP_PASS_LABEL_TEXT = u'Employee Password'
EMP_PASS_LABEL_TWO_TEXT = u'Reenter Employee Password'
HELP_OPTION_TEXT = u"Here you can create a new Employee Account. Fill in the fields, and click 'Submit' to do so."
INCORRECT_ADMIN_PASS_TEXT = u"Incorrect Admin Password."
LOGIN_FIELD_MISMATCH_TEXT = u"The Login fields didn't match."
LOGIN_FIELD_MISSING_TEXT = u"Please Enter an Employee Login"
PASS_DIGIT_TEXT = u"Your password must contain at least 1 Digit."
PASS_LENGTH_TEXT = u"Your password must contain at least 8 characters."
PASS_LOWERCASE_TEXT = u"Your password must contain at least 1 Lowercase letter."
PASS_MISMATCH_TEXT = u"The Password Fields didn't match."
PASS_UPPERCASE_TEXT = u"Your password must contain at least 1 Uppercase letter."
REGISTER_SCREEN_HELP_POPUP_TEXT = u"Here you can create your Employee account. You will require the administrator password to do so."
SECURITY_LABEL_TEXT = u"Security Question : "
SECURITY_ANSWER_LABEL_TEXT = u"Security Answer : "
SECURITY_HELP_TEXT = u"This is used to recover your password."
SECURITY_QUESTION_TEXT = u"Security Question"
SECURITY_QUESTION_ANSWER_TEXT = u"Security Answer"
SECURITY_VAR_FIRST_PET_TEXT = u"Name of First Pet"
SECURITY_VAR_FIRST_STREET_TEXT = u"Street you first lived in"
SECURITY_VAR_MAIDEN_NAME_TEXT = u"Mother's Maiden Name"
SECURITY_VAR_MEMORABLE_TEXT = u"Memorable Place"
USERNAME_IN_USE_TEXT = u"That Employee Login is already in use."
USERNAME_RESERVED_TEXT = u"That Employee Login is reserved."
