#SearchResultsScreenStringsEnglish

NAME_TEXT = u"Name: "
DEPARTMENT_TEXT = u"Department: "
DOB_TEXT = u"DOB: "
EMP_CODE_TEXT = u"Employee Code: "
FEMALE_TEXT = u"Female"
FEMALE_SINGLE_TEXT = u"F"
GENDER_TEXT = u"Gender: "
HELP_TEXT = u"This is the results screen for your search."
MALE_TEXT = u"Male"
MALE_SINGLE_TEXT = u"M"
SALARY_TEXT = u"Salary[Tax]: "
SPACE_TEXT = u"------------------------"
STAT_AVERAGE_SALARY_TEXT = u"Average Salary : "
STAT_AVERAGE_TAX_TEXT = u"Average Tax : "
STAT_TOTAL_EMP_TEXT = u"Total Employees : "
STAT_TOTAL_FEMALE_TEXT = u"Total Females : "
STAT_TOTAL_MALE_TEXT = u"Total Males : "
STAT_TOTAL_SALARY_TEXT = u"Total Salary : "
STAT_TOTAL_TAX_TEXT = u"Total Tax : "
STATS_AVERAGE_SALARY_TEXT = u"Average Salary"
STATS_AVERAGE_TAX_TEXT = u"Average Tax"
STATS_TOTAL_EMP_TEXT = u"Total Employees"
STATS_TOTAL_FEMALE_TEXT = u"Total Female"
STATS_TOTAL_MALE_TEXT = u"Total Male"
STATS_TOTAL_SALARY_TEXT = u"Total Salary"
STATS_TOTAL_TAX_TEXT = u"Total Tax"
