#SearchEmployeeScreen
 
BACK_BUTTON_TEXT = u"Back"
CODE_TEXT = u"Code"
DEPARTMENT_TEXT = u"Department"
DOB_TEXT = u"DOB"
DROPDOWN_DEPARTMENT_TEXT = u"Department"
DROPDOWN_DOB_TEXT = u"DOB"
DROPDOWN_EMPCODE_TEXT = u"Employee Code"
DROPDOWN_NAME_TEXT = u"Name"
DROPDOWN_SALARY_TEXT = u"Salary"
GENDER_TEXT = u"Gender"
HELP_OPTION_TEXT = u"Here you can search for employee records by field."
NAME_TEXT = u"Name"
NO_EMP_RECORDS_TEXT = u"There are no employee records."
REGISTER_BUTTON_TEXT = u"Create Account"
SALARY_TEXT = u"Salary"
SEARCH_BUTTON_TEXT = u"Search"
SEARCH_BY_TEXT = u"Search By: "
SEARCH_EMP_SCREEN_NONETYPE_ERROR_TEXT = u"Please enter Search Criteria."
SEARCH_FOR_TEXT = u"Search For: "
SEARCH_FOR_EMPLOYEES_TEXT = u"Search for Employees : "
SPACE_TEXT = u"------------------------"
