# -*- coding: utf-8 -*-
#SearchResultsScreenStringsGerman

NAME_TEXT = u"Name: "
DEPARTMENT_TEXT = u"Abteilung: "
DOB_TEXT = u"DOB: "
EMP_CODE_TEXT = u"Mitarbeiter-Code: "
FEMALE_TEXT = u"Weiblich"
FEMALE_SINGLE_TEXT = u"F"
GENDER_TEXT = u"Gehalt: "
HELP_TEXT = u"Dies ist der Bildschirm Ergebnisse für Ihre Suche."
MALE_TEXT = u"Männchen"
MALE_SINGLE_TEXT = u"M"
SALARY_TEXT = u"Gehalt: "
SPACE_TEXT = u"------------------------"
STAT_AVERAGE_SALARY_TEXT = u"Durchschnittsgehalt : "
STAT_AVERAGE_TAX_TEXT = u"Durchschnittliche Gebühr : "
STAT_TOTAL_EMP_TEXT = u"Gesamtzahl der Beschäftigten : "
STAT_TOTAL_FEMALE_TEXT = u"Gesamt Frauen : "
STAT_TOTAL_MALE_TEXT = u"Gesamt Männer : "
STATS_AVERAGE_SALARY_TEXT = u"Durchschnittsgehalt"
STATS_AVERAGE_TAX_TEXT = u"Durchschnittliche Steuer"
STATS_TOTAL_EMP_TEXT = u"Gesamtzahl der Beschäftigten"
STATS_TOTAL_FEMALE_TEXT = u"Gesamt Frauen"
STATS_TOTAL_MALE_TEXT = u"Gesamt Männer"
