# -*- coding: utf-8 -*-
#SearchEmployeeScreen
 
BACK_BUTTON_TEXT = u"Zurück"
CODE_TEXT = u"Code"
DEPARTMENT_TEXT = u"Abteilung"
DOB_TEXT = u"DOB"
DROPDOWN_DEPARTMENT_TEXT = u"Abteilung"
DROPDOWN_DOB_TEXT = u"DOB"
DROPDOWN_EMPCODE_TEXT = u"Mitarbeiter-Code"
DROPDOWN_NAME_TEXT = u"Name"
DROPDOWN_SALARY_TEXT = u"Gehalt"
GENDER_TEXT = u"Geschlecht"
HELP_OPTION_TEXT = u"Hier können Sie für Mitarbeiterdaten durch Feld suchen."
NAME_TEXT = u"Name"
NO_EMP_RECORDS_TEXT = u"Es gibt keine Mitarbeiterdatensätzen."
REGISTER_BUTTON_TEXT = u"Benutzerkonto erstellen"
SALARY_TEXT = u"Gehalt"
SEARCH_BUTTON_TEXT = u"Suche"
SEARCH_BY_TEXT = u"Suchen nach:"
SEARCH_EMP_SCREEN_NONETYPE_ERROR_TEXT = u"Bitte geben Sie die Suchkriterien."
SEARCH_FOR_TEXT = u"Suche Für: "
SEARCH_FOR_EMPLOYEES_TEXT = u"Suche nach Mitarbeitern: "
SPACE_TEXT = u"------------------------"
