# -*- coding: utf-8 -*-
#SearchEmployeeScreen
 
BACK_BUTTON_TEXT = u"Zurück"
CODE_TEXT = u"Code"
DEPARTMENT_TEXT = u"Department"
DOB_TEXT = u"DOB"
DROPDOWN_DEPARTMENT_TEXT = u"Abteilung"
DROPDOWN_DOB_TEXT = u"DOB"
DROPDOWN_EMPCODE_TEXT = u"Mitarbeiter-Code"
DROPDOWN_NAME_TEXT = u"Name"
DROPDOWN_SALARY_TEXT = u"Gehalt"
GENDER_TEXT = u"Gender"
HELP_OPTION_TEXT = u"Here you can search for employee records by field."
NAME_TEXT = u"Name"
REGISTER_BUTTON_TEXT = u"Benutzerkonto erstellen"
SALARY_TEXT = u"Salary"
SEARCH_BUTTON_TEXT = u"Suche"
SEARCH_BY_TEXT = u"Suchen nach:"
SEARCH_EMP_SCREEN_NONETYPE_ERROR_TEXT = u"Please enter Search Criteria."
SEARCH_FOR_TEXT = u"Suche Für: "
SEARCH_FOR_EMPLOYEES_TEXT = u"Suche nach Mitarbeitern: "
